for i in range(100):
    print("BUILD THIS AWESOME THING!!!")
    print("BUILD A BLIT ANIMATION TOOL FOR PYGAME WITH PANDAS DATAFRAMES")
    print("IT WOULD BE EPIC AND A GREAT WAY TO APPLY WHAT YOU LEARNED")
    print("YOU COULD USE DATA FRAME HEIRARCHIES TO BUILD IT AND IT WOULD BE AMAZIN BRUH")